### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.karapulse.Karapulse#3]

**Comment by gdesmott** [comment]
What's our policy? Always use the latest stable GNOME runtime?

**Comment by gdesmott** [comment]
Hum, has Python 2 been removed from the SDK? https://flathub.org/builds/#/builders/11/builds/649

**Comment by hadess** [comment]
> Hum, has Python 2 been removed from the SDK? https://flathub.org/builds/#/builders/11/builds/649

Would that help:
https://github.com/flathub/com.visualstudio.code.oss/blob/master/com.visualstudio.code.oss.json#L106

**Comment by gdesmott** [comment]
> > Hum, has Python 2 been removed from the SDK? https://flathub.org/builds/#/builders/11/builds/649
> 
> Would that help:
> https://github.com/flathub/com.visualstudio.code.oss/blob/master/com.visualstudio.code.oss.json#L106

No, same problem with this version: https://flathub.org/builds/#/builders/51/builds/633
